version: '3'
services:
  app:
    image: dyoshikawa/laravel:latest
    volumes:
      - .:/myproject
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: dyoshikawa/mysql:latest
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: development
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
